KNOWN_ALGORITHMS = {
    "binary search",
    "linear search",
    "selection sort",
    "bubble sort",
    "insertion sort",
    "merge sort",
    "quick sort",
    "heap sort",
    "dfs",
    "bfs",
    "linked list",
    "stack",
    "queue",
    "tree traversal",
    "graph traversal",
    "radix sort",
    "counting sort",
    "shell sort",
    "jump search",
    "interpolation search",
    "fibonacci search",
    "dijkstra",
    "kruskal",
    "prim",
    "bellman ford",
    "floyd warshall",
    "topological sort",
    "binary tree",
    "bst",
    "avl tree",
    "hash table",
    "union find",
}